PPortal/Controllers/AddPharmacyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class AddPharmacyController : Controller
    {
        // GET: AddPharmacy
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class AppointmentsController : Controller
    {
        // GET: Appointments
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Controllers/HealthLibraryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class HealthLibraryController : Controller
    {
        // GET: HealthLibrary
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class MessagesController : Controller
    {
        // GET: Messages
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Controllers/MyAppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class MyAppointmentsController : Controller
    {
        // GET: MyAppointments
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Controllers/MyChartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class MyChartsController : Controller
    {
        // GET: MyCharts
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Controllers/MyFormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class MyFormsController : Controller
    {
        // GET: MyForms
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Controllers/MyInsuranceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class MyInsuranceController : Controller
    {
        // GET: MyInsurance
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Controllers/MyMessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class MyMessagesController : Controller
    {
        // GET: MyMessages
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Controllers/MyProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class MyProfileController : Controller
    {
        // GET: MyProfile
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Controllers/RecoverPasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class RecoverPasswordController : Controller
    {
        // GET: RecoverPassword
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class RegistrationController : Controller
    {
        // GET: Registration
        public ActionResult Index(string id)
        {
            return View();
        }
    }
}

PPortal/Controllers/RequestAppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class RequestAppointmentController : Controller
    {
        // GET: RequestAppointment
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Controllers/RequestRefillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPortal.Controllers
{
    public class RequestRefillController : Controller
    {
        // GET: RequestRefill
        public ActionResult Index()
        {
            return View();
        }
    }
}

PPortal/Views/Appointments/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<!-- Bread crumb and right sidebar toggle -->
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Appointments</h4>
    </div>
    <div class="col-md-7 align-self-center text-right">
        <div class="d-flex justify-content-end align-items-center">
            <a href="@Url.Action("Index","RequestAppointment")" class="btn btn-info d-lg-block m-l-15"><i class="fa fa-plus-circle"></i>&nbsp;Request a new appointment</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header bg-info">
                <h4 class="m-b-0 text-white"><b>Upcoming Appointments</b></h4>
            </div>
            <div class="card-body">
                <form action="#">
                    <div class="form-body">
                        <h4 class="card-title">You have no upcoming appointments</h4>
                        <hr>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header bg-info">
                <h4 class="m-b-0 text-white"><b>Past Appointments</b></h4>
            </div>
            <div class="card-body">
                <form action="#">
                    <div class="form-body">
                        <div class="table-responsive">
                            <div id="example23_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                                <table id="example23" class="display nowrap table table-hover table-striped table-bordered dataTable" cellspacing="0" width="100%" role="grid" aria-describedby="example23_info" style="width: 100%;">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="example23" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 118px;">Name</th>
                                            <th class="sorting" tabindex="0" aria-controls="example23" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 186px;">Position</th>
                                            <th class="sorting" tabindex="0" aria-controls="example23" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 85px;">Office</th>
                                            <th class="sorting" tabindex="0" aria-controls="example23" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 29px;">Age</th>
                                            <th class="sorting" tabindex="0" aria-controls="example23" rowspan="1" colspan="1" aria-label="Start date: activate to sort column ascending" style="width: 74px;">Start date</th>
                                            <th class="sorting" tabindex="0" aria-controls="example23" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 58px;">Salary</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">Airi Satou</td>
                                            <td>Accountant</td>
                                            <td>Tokyo</td>
                                            <td>33</td>
                                            <td>2008/11/28</td>
                                            <td>$162,700</td>
                                        </tr>
                                        <tr role="row" class="even">
                                            <td class="sorting_1">Angelica Ramos</td>
                                            <td>Chief Executive Officer (CEO)</td>
                                            <td>London</td>
                                            <td>47</td>
                                            <td>2009/10/09</td>
                                            <td>$1,200,000</td>
                                        </tr>
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">Ashton Cox</td>
                                            <td>Junior Technical Author</td>
                                            <td>San Francisco</td>
                                            <td>66</td>
                                            <td>2009/01/12</td>
                                            <td>$86,000</td>
                                        </tr>
                                        <tr role="row" class="even">
                                            <td class="sorting_1">Bradley Greer</td>
                                            <td>Software Engineer</td>
                                            <td>London</td>
                                            <td>41</td>
                                            <td>2012/10/13</td>
                                            <td>$132,000</td>
                                        </tr>
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">Brenden Wagner</td>
                                            <td>Software Engineer</td>
                                            <td>San Francisco</td>
                                            <td>28</td>
                                            <td>2011/06/07</td>
                                            <td>$206,850</td>
                                        </tr>
                                        <tr role="row" class="even">
                                            <td class="sorting_1">Brielle Williamson</td>
                                            <td>Integration Specialist</td>
                                            <td>New York</td>
                                            <td>61</td>
                                            <td>2012/12/02</td>
                                            <td>$372,000</td>
                                        </tr>
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">Bruno Nash</td>
                                            <td>Software Engineer</td>
                                            <td>London</td>
                                            <td>38</td>
                                            <td>2011/05/03</td>
                                            <td>$163,500</td>
                                        </tr>
                                        <tr role="row" class="even">
                                            <td class="sorting_1">Caesar Vance</td>
                                            <td>Pre-Sales Support</td>
                                            <td>New York</td>
                                            <td>21</td>
                                            <td>2011/12/12</td>
                                            <td>$106,450</td>
                                        </tr>
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">Cara Stevens</td>
                                            <td>Sales Assistant</td>
                                            <td>New York</td>
                                            <td>46</td>
                                            <td>2011/12/06</td>
                                            <td>$145,600</td>
                                        </tr>
                                        <tr role="row" class="even">
                                            <td class="sorting_1">Cedric Kelly</td>
                                            <td>Senior Javascript Developer</td>
                                            <td>Edinburgh</td>
                                            <td>22</td>
                                            <td>2012/03/29</td>
                                            <td>$433,060</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

PPortal/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Dashboard</h4>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header bg-info text-center">
                <h4 class="mb-0 text-white">Good afternoon, User</h4>
            </div>
            <div class="card-body text-center">
                <h4 class="card-title">What would you like to do today?</h4>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-12 col-xs-12">
        <a href="@Url.Action("Index","Appointments")">
            <div class="card">
                <div class="card-body text-center">
                    @*<img src="Content/images/orangeappointment.png" />*@
                    <img src="Content/images/appointment.png" />
                    <h3 class="card-title" style="margin-top: 10px;">
                        Schedule an
                        <br />
                        appointment
                    </h3>
                </div>
            </div>
        </a>
    </div>
    <div class="col-md-4 col-sm-12 col-xs-12">
        <a href="@Url.Action("Index","Messages")">
            <div class="card">
                <div class="card-body text-center">
                    @*<img src="Content/images/orangeemail.png" />*@
                    <img src="Content/images/email.png" />
                    <h3 class="card-title" style="margin-top: 10px;">
                        Send a
                        <br />
                        message
                    </h3>
                </div>
            </div>
        </a>
    </div>
    <div class="col-md-4 col-sm-12 col-xs-12">
        <a href="@Url.Action("Index","RequestRefill")">
            <div class="card">
                <div class="card-body text-center">
                    @*<img src="Content/images/orangerefill.png" />*@
                    <img src="Content/images/refill.png" />
                    <h3 class="card-title" style="margin-top: 10px;">
                        Request
                        <br />
                        a refill
                    </h3>
                </div>
            </div>
        </a>
    </div>
</div>

PPortal/Views/Messages/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<!-- Bread crumb and right sidebar toggle -->
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Messages</h4>
    </div>
    <div class="col-md-7 align-self-center text-right">
        <div class="d-flex justify-content-end align-items-center">
            <button type="button" class="btn btn-info d-lg-block m-l-15" data-toggle="modal" data-target="#exampleModal"><i class="fa fa-plus-circle"></i>&nbsp;Compose New Message</button>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-info alert-rounded m-b-10">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span> </button>
            <i class="fa fa-check-circle"></i>&nbsp;Welcome to the "Some" Primary Care Physicians secure Patient Portal.<br /><br />
            This portal is available for information and for the convenience of our patients. It is NOT intended for diagnosis or treatment of medical problems. Please Note:
            Messages left on the Patient Portal are for NON URGENT communications with your physician and may not be reviewed for up to 72 hours.
        </div>
        <div class="card">
            <div class="card-header bg-info">
                <h4 class="m-b-0 text-white"><b>New Messages</b></h4>
            </div>
            <div class="card-body">
                <form action="#">
                    <div class="form-body">
                        <h4 class="card-title">You have no new messages</h4>
                        <hr>
                    </div>
                </form>
                <div class="modal bs-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
                    <div class="modal-dialog modal-xl" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="exampleModalLabel1">Compose New message</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            </div>
                            <div class="modal-body">
                                <form>
                                    <div class="form-body">
                                        <div class="form-group row m-b-5">
                                            <label for="recipient-name" class="control-label p-l-10">Please note that you can expect to receive a response within 24 hours.</label>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <label class="col-md-3" style="text-align:right">On behalf of:</label>
                                                    <div class="col-md-6">
                                                        <select class="custom-select col-12" id="inlineFormCustomSelect">
                                                            <option selected="">Choose...</option>
                                                            <option value="1">One</option>
                                                            <option value="2">Two</option>
                                                            <option value="3">Three</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <label class="col-md-3" style="text-align:right">Practice:</label>
                                                    <div class="col-md-6">
                                                        <select class="custom-select col-12" id="inlineFormCustomSelect1">
                                                            <option selected="">Choose...</option>
                                                            <option value="1">One</option>
                                                            <option value="2">Two</option>
                                                            <option value="3">Three</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <label class="col-md-3" style="text-align:right">Location:</label>
                                                    <div class="col-md-6">
                                                        <select class="custom-select col-12" id="inlineFormCustomSelect2">
                                                            <option selected="">Choose...</option>
                                                            <option value="1">One</option>
                                                            <option value="2">Two</option>
                                                            <option value="3">Three</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <label class="col-md-3" style="text-align:right">To:</label>
                                                    <div class="col-md-6">
                                                        <select class="custom-select col-12" id="inlineFormCustomSelect3">
                                                            <option selected="">Choose...</option>
                                                            <option value="1">One</option>
                                                            <option value="2">Two</option>
                                                            <option value="3">Three</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <label class="col-md-3" style="text-align:right">Subject:</label>
                                                    <div class="col-md-9">
                                                        <input type="text" class="form-control" runat="server" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <label class="col-md-3" style="text-align:right"><i class="fas fa-link"></i></label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <div class="col-md-12">
                                                        <textarea id="mymce" name="area" rows="8" cols="10" class="form-control" placeholder="Please enter your message here"></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
                                <a href="@Url.Action("Index","MyMessages")" class="btn btn-info">Send message</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PPortal/Views/MyForms/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<!-- Bread crumb and right sidebar toggle -->
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Forms</h4>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header bg-info">
                <h4 class="m-b-0 text-white"><b>Pending Forms</b></h4>
            </div>
            <div class="card-body">
                <form action="#">
                    <div class="form-body">
                        <div class="table-responsive">
                            <table class="table color-table primary-table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Date Received</th>
                                        <th>Title</th>
                                        <th>Practice</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td colspan="4">
                                            No pending forms to display.
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header bg-info">
                <h4 class="m-b-0 text-white"><b>Completed Forms</b></h4>
            </div>
            <div class="card-body">
                <form action="#">
                    <div class="form-body">
                        <div class="table-responsive">
                            <table class="table color-table primary-table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Date Received</th>
                                        <th>Title</th>
                                        <th>Practice</th>
                                        <th>Reviewd On</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td colspan="4">
                                            No completed forms to display.
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header bg-info">
                <h4 class="m-b-0 text-white"><b>Available Forms</b></h4>
            </div>
            <div class="card-body">
                <form action="#">
                    <div class="form-body">
                        <div class="table-responsive">
                            <table class="table color-table primary-table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Title</th>
                                        <th>Practice</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td colspan="4">
                                            No available forms to display.
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>